### ISSUE TITLE
Error when Build file exe for windown - Unity

### ISSUE THREAD

**Issue by kvtem** [jackyyang09/Simple-Unity-Audio-Manager#11]
Hello everyone!
I build to file exe in unity then have issue. 
if remove package then build work; 
![image](https://user-images.githubusercontent.com/30280030/123411320-85d75280-d5da-11eb-90d9-ecec0ba8503c.png)

**Comment by colseed** [comment]
I think the "Could not find a part of the path" error is due to the folder name having an apostrophe in it - I saw a similar build error in 2020.3 and was able to fix it by renaming the JSAM folder to remove the apostrophe. 

(apostrophes in folder names used to work in older unity versions so presumably this is due to unity changing something)

**Comment by kvtem** [comment]
thanks you for your reply. i will try way for next time
