### ISSUE TITLE
when audio file is deleted, Audio File scriptable object becomes unusable

### ISSUE THREAD

**Issue by Aledavid07** [jackyyang09/Simple-Unity-Audio-Manager#33]
![image](https://github.com/jackyyang09/Simple-Unity-Audio-Manager/assets/70920098/7125e884-2c3f-44c5-aba9-ef61274de14c)

![image](https://github.com/jackyyang09/Simple-Unity-Audio-Manager/assets/70920098/3d49773f-42ed-4f03-8f96-956402618a49)

I guess its just that the Custom Inspector Code cant perform the next lines of code because theres no reference for the audio file in one line of code. And it doesn't let me drag another audio file or literally change anything in the scriptable object.

**Comment by jackyyang09** [comment]
Thanks for reporting, this issue will be fixed in the next release. If you're still experiencing this issue, you can work around it by toggling debug mode in your Inspector when working with the SoundFileObject. 

You can do this by right-clicking your Inspector window, clicking the `Debug` option, and then manually removing the missing array element. Once that's done you can switch your Inspector back to the `Normal` option.
