### ISSUE TITLE
GC on AudioManager.PlaySound

### ISSUE THREAD

**Issue by StinkySteak** [jackyyang09/Simple-Unity-Audio-Manager#35]
![image](https://github.com/jackyyang09/Simple-Unity-Audio-Manager/assets/52377879/1f4385b7-807b-4173-9c4a-bf620d25dd52)

Is there a way to solve this?
JSAM Version: 0.3.0-preview-6
Unity: 2021.3.38.f1 Editor

**Comment by Bezhok** [comment]
![image](https://github.com/jackyyang09/Simple-Unity-Audio-Manager/assets/30340548/055ff3c4-a1de-408e-aec6-99afa21951c1)
it is the reason

**Comment by Bezhok** [comment]
something like this 
![image](https://github.com/jackyyang09/Simple-Unity-Audio-Manager/assets/30340548/f9ea42dd-64f5-41e9-9a94-d18a6bb7329c)
![image](https://github.com/jackyyang09/Simple-Unity-Audio-Manager/assets/30340548/f4d0a93d-0b6f-46b5-a22b-b8e07a391b5f)

store channel instead of delegatte, than reset it

**Comment by jackyyang09** [comment]
Sorry for the wait, and thanks for pointing this issue out, Bezhok's fix has been incorporated in the new [Version 3.0.1 Release](https://github.com/jackyyang09/Simple-Unity-Audio-Manager/releases/tag/v3.0.1)
