### ISSUE TITLE
Enhancement suggestion to enum system leveraging categories

### ISSUE THREAD

**Issue by khiemgluong** [jackyyang09/Simple-Unity-Audio-Manager#47]
The new Audio Library system looks promising but there's a disadvantage over my currently made one which prevents me to adopting this asset, and maybe for others as well. 
The Audio Library allows creating categories for Sound and Music, but this category is not put to use at runtime. This means there's only two sets of enums to make calls to, where the categories are just editor based and have no purpose at runtime.
I was thinking that rather than have 2 enums that stores LibrarySounds and LibraryMusic, it would instead have 2 classes with several enums within it, representing the categories that was made in that library.
For example, my sounds library would have a category of Hit and Swing, and when I generate the audio library, a class called SoundLibraryEnums would generate with 2 enums, Hit and Swing, corresponding to those categories:

```cs
public class NewAudioLibrarySounds
{
  public enum Hit{
    SoundA,
    SoundB
  }
  public enum Swing{
    SoundA,
    SoundB
  }
}
```

Instead of the current way of:
```cs
public enum NewAudioLibrarySounds {
  HitSoundA,
  HitSoundB,
  SwingSoundA,
  SwingSoundB
 }
```

At runtime, this would afford you a more efficient way of organizing sounds. So instead of choosing from a potentially massive enum of all your sounds/music, you can access the specific enum from the Sounds or Music class and retrieve the only the enum within it. Furthermore, you can reuse the same enum name as long as it doesn't conflict within the enum category that it's in.
Before
```cs
AudioManager.PlaySound(NewAudioLibrarySounds.HitSoundA);//4 entries to search through
```
After 
```cs
AudioManager.PlaySound(NewAudioLibrarySounds.Hit.SoundA);//only 2 entries to search through
```

**Comment by jackyyang09** [comment]
Hi khiemgluong,

Thanks for the suggestion, extending the enum generation to take categories into account would make searching for your specific sound enum much easier. However, the new Audio Library updates are a reflection of the current direction I'd like JSAM to move in. 

Ideally, your project should be made up of several smaller Audio Libraries that you'd load (and unload) during runtime as you need them. As such, there should be less of a need for deeper categorization for enums since each Library can have its own set of unique enums. This is a departure from the workflow encouraged in earlier versions of JSAM where a single, large, Audio Library containing all your project's audio was loaded at the start and would stay throughout.

Ultimately it's my own fault for not advertising these changes better. I'd like to update the documentation at some point but I haven't gotten the chance to do so yet.

Regardless, I appreciate you taking the time to bring this issue up. Hope this helps!
