### ISSUE TITLE
Enums fail when song starts with int

### ISSUE THREAD

**Issue by willWashington** [jackyyang09/Simple-Unity-Audio-Manager#5]
The first song in my list of songs starts with the number "5".
AudioEnums.cs blows up on the Music enum when the enum value starts with an integer.

**Comment by jackyyang09** [comment]
Thanks for filing a report! However, due to the nature of C# property names being unable to start with integers, this issue cannot be fixed. As a workaround, you can use integers in any other index of your name (ie. _001Track, Track001, -001) so long as the name starts with a letter or other symbol not used by the compiler.

I'll be adding some functionality for the next release that will warn you if you try to do otherwise and have the system strip numbers at the start of the name as a fallback.
